### ISSUE TITLE
Serverless throws error when throttling limit sets for endpoint

### ISSUE THREAD

**Issue by NitroCat** [DianaIonita/serverless-api-gateway-throttling#2]
Hello,
I've installed and configured serverless-api-gateway-throttling in serverless.yaml as follows:
```yaml
service: some-service-name
#...
custom:
#...
   stage: "some-stage"
   apiGatewayCaching:
      enabled: true
   apiGatewayThrottling:
      maxRequestsPerSecond: 50
      maxConcurrentRequests: 50
#...
functions:
#...
  health-check:
     role: someHealthCheckRole
     handler: src/handlers/health-check/handler.handler
     events:
       - http:
           path: /v1/health-check
           method: GET
           throttling:
             maxRequestsPerSecond: 2
             maxConcurrentRequests: 2
#...
resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:service}-${self:custom.stage}
#...
```

execute:
```sh
sls deploy --stage some-stage
```

**Actual result:**
Serverless throws:
```sh
Serverless Error ---------------------------------------
 
Function "some-service-name-some-stage-health-check" doesn't exist in this Service

```

**Expected result**
Everything deployed successfully and throttling configuration applies to endpoint

After debugging looks like:

- that line throws error
https://github.com/DianaIonita/serverless-api-gateway-throttling/blob/48b920aeda3538ef7c0fa7926f7b93fd15e4bb3b/src/updateStageThrottling.js#L84
It tries to get function with name `some-service-name-some-stage-health-check` instead of `health-check` which is presented in `serverless.service`

- What is the purpose use `customFunctionName` or `functionName`. It should get function by some one name 
https://github.com/DianaIonita/serverless-api-gateway-throttling/blob/48b920aeda3538ef7c0fa7926f7b93fd15e4bb3b/src/ApiGatewayThrottlingSettings.js#L19

Node.js: v10.15.3
Serverless: v1.54.0

It's very usefull serverless plugin and I hope bug will be fixed =)
