### ISSUE TITLE
HttpApiIdForApigThrottling error

### ISSUE THREAD

**Issue by stanislav-web** [DianaIonita/serverless-api-gateway-throttling#25]
After update from 1.2.2 -> to 2.0.0 i am catching error `Could not find stack output variable named HttpApiIdForApigThrottling` while `sls deploy`

Throttling has configured on root level
```
custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500
```
