### ISSUE TITLE
Error: Expected params.restApiId to be a string

### ISSUE THREAD

**Issue by mlewis7127** [DianaIonita/serverless-api-gateway-throttling#27]
When using this plugin with serverless framework v3 and referencing a restApi from another stack, I get an error that it expected params.restApiId to be a string.

For one stack I use the following serverless.yml file
[serverless.yml.zip](https://github.com/DianaIonita/serverless-api-gateway-throttling/files/9135599/serverless.yml.zip)

The next stack uses the following serverless.yml from a base aws-nodejs template:
[serverless.yml.zip](https://github.com/DianaIonita/serverless-api-gateway-throttling/files/9135603/serverless.yml.zip)

If I remove the throttling plugin the error message goes away.

**Comment by DianaIonita** [comment]
Hi @mlewis7127,

Thanks for reporting the issue.
Could you please try executing `sls print` ([reference](https://www.serverless.com/framework/docs/providers/aws/cli-reference/print)) in your repository and checking whether the `restApiId` value is properly filled in?

I'll paste a sample of your yml here for easier reference and so that search engines have a chance to index it:

```yml
provider:
  name: aws
  runtime: nodejs16.x
  apiGateway:
    restApiId: !ImportValue DemoApiGW-restApiId
    restApiRootResourceId: !ImportValue DemoApiGW-rootResourceId

plugins:
  - serverless-api-gateway-throttling

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500
```
