### ISSUE TITLE
Error: settings.httpApiEndpointSettings is not iterable

### ISSUE THREAD

**Issue by Lpfigueiredo** [DianaIonita/serverless-api-gateway-throttling#30]
Hi! I'm trying to use the plugin but i'm getting the following error when running `serverless deploy`:

> TypeError: settings.httpApiEndpointSettings is not iterable
>     at updateHttpApi (C:\cursos\serverless_test\aws-node-http-api-project\node_modules\serverless-api-gateway-throttling\src\updateHttpApiStageThrottling.js:9:52)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async ApiGatewayThrottlingPlugin.updateStage (C:\cursos\serverless_test\aws-node-http-api-project\node_modules\serverless-api-gateway-throttling\src\apiGatewayThrottlingPlugin.js:67:7)

My serverless.yml is:
```
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-api-gateway-throttling

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
          throttling:
            maxRequestsPerSecond: 3000
            maxConcurrentRequests: 1000
```

I'm using the Serverless HTTP API example. When I disable the plugin, the deployment occurs normally. I tried to re-deploy but the error persists.

Can you help me, please?
Thanks

**Comment by DianaIonita** [comment]
Hi @Lpfigueiredo,

Please check that you've configured the plugin like in the example in the Readme.
Your `serverless.yml` doesn't show `custom.apiGatewayThrottling` settings:

```yml
plugins:
  - serverless-api-gateway-throttling

custom:
  # Configures throttling settings for the API Gateway stage
  # They apply to all http endpoints, unless specifically overridden
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500
```

Let me know if you're still having problems after that.
