### ISSUE TITLE
Cannot change path of httpApi event on lambda

### ISSUE THREAD

**Issue by HancoVisagie** [DianaIonita/serverless-api-gateway-throttling#33]
Take this for example

```
  World:
    name: ${self:service}-${self:provider.stage}-WorldFunction
    handler: ${self:custom.handler.prefix}.UserHandler::World
    events:
      - httpApi:
          method: GET
          path: /world
```

deploy this, works fine, then do this:

```
  World:
    name: ${self:service}-${self:provider.stage}-WorldFunction
    handler: ${self:custom.handler.prefix}.UserHandler::World
    events:
      - httpApi:
          method: GET
          path: /world2
```

and I get the following error:
Unable to find Route by key GET /world within the provided RouteSettings

Disable the extension and deployment succeeds.
