### ISSUE TITLE
Need Help Setting Throttling Limits for a Single API Method Without Affecting Others in Serverless Framework

### ISSUE THREAD

**Issue by LakhsmikanthD** [DianaIonita/serverless-api-gateway-throttling#39]
Hi,

I encountered an issue similar to [this one](https://github.com/DianaIonita/serverless-api-gateway-throttling/issues/37). I applied the suggested code:

```yaml
custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: -1
    maxConcurrentRequests: -1
```

However, this code deactivates the rate and burst limits for all API methods except the one where I set custom limits. Can anyone help me modify the throttling settings for a single method in a specific stage without affecting the other methods?
