### ISSUE TITLE
Per method throttling config is not being deleted on redeployment

### ISSUE THREAD

**Issue by lkolchin** [DianaIonita/serverless-api-gateway-throttling#5]
Hi,

I've deployed the config per method and verified that it was deployed.
But when I removed it from serverless.yaml and left Throttling config as a Global setting - The per method config was not deleted on redeployment.

Before:
```
custom:
  serverless-jetpack:
    mode: npm # (default `yarn`)
  # Configures throttling settings for all http endpoints
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500

  landingPage1:
    role: landingPageRole
    handler: src/handler1.landingPage
    package:
      exclude:
        - "**/**"
      include:
        - src/handler1.js
    events:
      - http:
          path: 'landingPage1'
          method: get
          cors: true
          throttling:
            maxRequestsPerSecond: 2000
            maxConcurrentRequests: 1000
    environment:
      BG_COLOUR: ${self:custom.backgroundColour.${self:provider.stage}} 
```

After:
```
custom:
  serverless-jetpack:
    mode: npm # (default `yarn`)
  # Configures throttling settings for all http endpoints
  apiGatewayThrottling:
    maxRequestsPerSecond: 1000
    maxConcurrentRequests: 500

  landingPage1:
    role: landingPageRole
    handler: src/handler1.landingPage
    package:
      exclude:
        - "**/**"
      include:
        - src/handler1.js
    events:
      - http:
          path: 'landingPage1'
          method: get
          cors: true
    environment:
      BG_COLOUR: ${self:custom.backgroundColour.${self:provider.stage}} 
```
