### ISSUE TITLE
Does not work with "serverless-aws-alias" plugin

### ISSUE THREAD

**Issue by ValeryP** [DianaIonita/serverless-api-gateway-throttling#6]
I've realized that the plugin does not work for aliases. Every time I deploy to any alias it performs all actions on the stage instead of the alias name.

Plugins:
```
plugins:
  - serverless-python-requirements
  - serverless-aws-alias
  - serverless-api-gateway-caching
  - serverless-api-gateway-throttling
```

Fun:
```
functions:
  energy:
    handler: src/handler.energy
    package: {}
    events:
      - http:
          path: energy
          method: get
          cors: true
          private: true
          apiGatewayThrottling:
            maxRequestsPerSecond: 10
            maxConcurrentRequests: 5
```

Am I doing something wrong or is there any workaround? Thanks!

P.S. Sorry for the template text of the issue but it seems I became a hard user of your plugins 😄
