### ISSUE TITLE
Serverless: Configuration warning at 'functions['export-latest'].events[0].http': unrecognized property 'throttling'

### ISSUE THREAD

**Issue by crushjelly** [DianaIonita/serverless-api-gateway-throttling#9]
I am getting this warning `Serverless: Configuration warning at 'functions['export-latest'].events[0].http': unrecognized property 'throttling'` when using http event. 
```

    events:
      - http:
          path: export/item
          method: get
          private: true
          throttling:
            maxRequestsPerSecond: 2000
            maxConcurrentRequests: 1000
```

When I use global _apiGatewayThrottling_ configuration it works fine.
Is my configuration bad?
